[package]
name = "learn-http"
version = "0.1.0"
authors = ["kawakami <kawakami.ozone@gmail.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "http-server"
path = "src/http-server.rs"

[[bin]]
name = "http-client"
path = "src/http-client.rs"

